#!/bin/bash -x
# Run this script with
# curl -s -L https://raw.githubusercontent.com/darrylb123/MensShed/main/Computers/Fedora-Cinnamon-install | sudo bash

# Update the computer
dnf -y update 

# install git
dnf -y install git

# Install gnome-software
dnf -y install fedora-workstation-repositories gnome-software

# Install the Cinnamon desktop
dnf -y groupinstall 'Cinnamon Desktop'

#enable the 3rd party repositories
dnf config-manager --enable google-chrome
dnf config-manager --enable copr:copr.fedorainfracloud.org:phracek:PyCharm
dnf config-manager --enable rpmfusion-nonfree-nvidia-driver
dnf config-manager --enable rpmfusion-nonfree-steam



# Install additional packages
dnf -y install google-chrome-stable gimp inkscape

# Flatpak is installed with gnome-software
# enable flathub repository
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

# Install FreeCAD 
flatpak install flathub org.freecadweb.FreeCAD -y --noninteractive

#Install Bambu Studio
flatpak install flathub com.bambulab.BambuStudio -y --noninteractive

#Install Converter Now
flatpak install flathub io.github.ferraridamiano.ConverterNOW -y --noninteractive

# start the ssh daemon to enable remote admin
systemctl enable sshd
systemctl start sshd

# Install Lightburn
LB=$(curl -s  https://api.github.com/repos/LightBurnSoftware/deployment/releases/latest | grep AppImage | grep browser_download_url | cut -d\"  -f 4)
LBFILE=$(basename $LB)
echo "Installing $LB"
if [ -f "Desktop/$LBFILE" ]
then
        echo "$LBFILE already installed"
else
        pwd
        MYID=$(basename $(pwd))
        ( cd Desktop; curl -OL  $LB ; chmod +x $LBFILE ;chown $MYID:$MYID $LBFILE )
fi

echo "Please reboot at your convenience"
