#!/bin/bash -x
# Update the computer
dnf -y update 

# install git
dnf -y install git

# Install gnome-software
dnf -y install fedora-workstation-repositories gnome-software

# Flatpak is installed with gnome-software
# enable flathub repository
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

# Install google chrome
dnf -y install google-chrome-stable

# Install FreeCAD from flathub
flatpak install flathub org.freecadweb.FreeCAD -y

#install Bambu Studio
flatpak install flathub com.bambulab.BambuStudio -y

