#!/bin/bash -x
# Run this script with
# curl -s -L https://raw.githubusercontent.com/darrylb123/MensShed/main/Computers/Fedora-Cinnamon-install | sudo bash

# Update the computer
dnf -y update 

# install git
dnf -y install git

# Install gnome-software
dnf -y install fedora-workstation-repositories gnome-software

#enable the 3rd party repositories
dnf config-manager --enable google-chrome
dnf config-manager --enable copr:copr.fedorainfracloud.org:phracek:PyCharm
dnf config-manager --enable rpmfusion-nonfree-nvidia-driver
dnf config-manager --enable rpmfusion-nonfree-steam


# Flatpak is installed with gnome-software
# enable flathub repository
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

# Install google chrome
dnf -y install google-chrome-stable

# Install FreeCAD from flathub
flatpak install flathub org.freecadweb.FreeCAD -y

#install Bambu Studio
flatpak install flathub com.bambulab.BambuStudio -y


# start the ssh daemon to enable remote admin
systemctl enable sshd
systemctl start sshd
